# This is a basic workflow to help you get started with Actions

name: vinix

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: build
        run: |
          sudo apt update
          sudo apt install --fix-missing build-essential nasm git subversion mtools meson m4 texinfo pkg-config groff gettext autopoint bison flex help2man libssl-dev gperf rsync xsltproc python3 python3-pip python3-mako wget xorriso qemu-system-x86
          git clone --depth 1 https://github.com/vlang/vinix.git
          git branch remotes/origin/linux-binary-compat
          pip3 install --user xbstrap
          cd vinix
          make distro
          make
          

